[package]
name = "simple_layout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.8"
log = "0.4.20"
env_logger = "0.10.1"
embedded-graphics-simulator = { version = "0.6.0", optional = true }

[dev-dependencies]
chrono = "0.4.31"

[features]
simulate-example = ["embedded-graphics-simulator"]