[package]
name = "simple_layout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.8"

[dev-dependencies]
embedded-graphics-simulator = "0.6.0"
chrono = "0.4.31"